### ISSUE TITLE
Move `pool.ts` to `src` so the root dir only contains config files

### ISSUE THREAD

**Issue by ForsakenHarmony** [kristoferbaxter/async#3]

**Comment by kristoferbaxter** [comment]
A good first issue here, but I'll try to address quickly.

**Comment by ForsakenHarmony** [comment]
Why is tsconfig in there as well? 🙈

**Comment by kristoferbaxter** [comment]
In my experience it’s been easier to adapt tsconfig when it’s scoped to the most direct shared folder of the files it acts on.

So, in this case, only src/ is configured.

**Comment by ForsakenHarmony** [comment]
right
